// tslint:disable
/**
 * Foo Bar
 * null
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    User,
    UserFromJSON,
    UserToJSON,
} from '../models';

export interface UsersSendPasswordReminderPostRequest {
    user?: User;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Add a new user to the database
     */
    async usersSendPasswordReminderPostRaw(requestParameters: UsersSendPasswordReminderPostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/send-password-reminder`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters.user),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a new user to the database
     */
    async usersSendPasswordReminderPost(requestParameters: UsersSendPasswordReminderPostRequest): Promise<void> {
        await this.usersSendPasswordReminderPostRaw(requestParameters);
    }

}
